fixed SolverManager.solver() description typo
kiegroup/optaplanner pull request #1055
Opened 2020-12-01 09:35 UTC by IanShow15

### Checklist
- [ ] Documentation: PlannerConfiguration-SolverManager description clarification

<details>
<summary>
fixed SolverManager description typo
</summary>
</details>

2020-12-01 09:36 UTC, IanShow15 commented
ok to test

2020-12-01 09:36 UTC, triceo commented
ok to test.

2020-12-01 09:44 UTC, triceo requested changes
@IanShow15 Thank you for your contribution.

I have reviewed the doc in question and have figured out what it was supposed to mean.
I am suggesting a clarification that makes the true meaning of the text obvious. 

Please accept my suggestions by clicking on the appropriate buttons. I will merge afterwards.

2020-12-01 09:44 UTC, triceo commented on optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
>  Its `solve(...)` methods differ from the normal `Solver.solve(...)` method:
```suggestion
Unlike the `Solver.solve(...)` method:
```

2020-12-01 09:44 UTC, triceo commented on optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
> +* *`Solver.solve(...)` returns immediately*: it schedules a problem for asynchronous solving without blocking the calling thread.
```suggestion
* *`SolverManager.solve(...)` returns immediately*: it schedules a problem for asynchronous solving without blocking the calling thread.
```

2020-12-02 08:56 UTC, merged

2020-12-02 08:56 UTC, triceo commented
Thank you!