Only run full profile on Jenkins
kiegroup/optaplanner pull request #1294
Opened 2021-04-28 09:03 UTC by triceo

2021-04-28 09:32 UTC, rsynek approved these changes
One suggestion to increase the chance we won't forget to test the full profile with the new JDK.

2021-04-28 09:32 UTC, rsynek commented on .github/workflows/os_java_ci.yml
>    # TODO: update each time a new major Java version is released.
```suggestion
  # TODO: Update each time a new major Java version is released. Make sure you build OptaPlanner with the full profile locally with the new Java version first.
```

2021-04-28 09:49 UTC, ge0ffrey requested changes
I 'd rather stop relying on Jenkins. It's not reliable.
Many important checks only happen in the full profile.

2021-05-13 07:01 UTC, triceo commented
There is no consensus on this.

2021-05-13 07:01 UTC, closed without merging