Test Build Chain
kiegroup/optaplanner pull request #1347
Opened 2021-05-27 09:17 UTC by radtriste

### JIRA

### Referenced pull requests

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
</details>

2021-05-27 09:21 UTC, danielezonca commented
@radtriste 
Can you please apply the same fix of this PR?
https://github.com/kiegroup/drools/pull/3642/files
Otherwise the risk is to mix m2 created with different jdk versions

2021-05-27 13:11 UTC, danielezonca commented on .github/workflows/os_java_ci.yml
> +          report_paths: '**/*-reports/TEST-*.xml'
```suggestion
        uses: ScaCap/action-surefire-report@v1.0.10
        with:
          fail_on_test_failures: true
          fail_if_no_tests: false
          skip_publishing: true
          report_paths: '**/*-reports/TEST-*.xml'
```

2021-05-27 13:11 UTC, danielezonca commented on .github/workflows/os_java_ci.yml
> +          report_paths: '**/*-reports/TEST-*.xml'
```suggestion
        uses: ScaCap/action-surefire-report@v1.0.10
        with:
          fail_on_test_failures: true
          fail_if_no_tests: false
          skip_publishing: true
          report_paths: '**/*-reports/TEST-*.xml'
```

2021-06-02 07:59 UTC, Ginxo requested changes
please change `Publish Test Report` step for both flows since changes from `ginxo/action-surefire-report@BXMSPROD-1311` has been merged to original project

2021-06-02 07:59 UTC, Ginxo commented on .github/workflows/os_java_ci.yml
> +        uses: ginxo/action-surefire-report@BXMSPROD-1311
please replace `Publish Test Report` by

```
      - name: Check Surefire Report
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1.0.10
        with:
          fail_on_test_failures: true
          fail_if_no_tests: false
          skip_publishing: true.
          report_paths: '**/*-reports/TEST-*.xml'
```

2021-06-02 07:59 UTC, Ginxo commented on .github/workflows/os_java_ci.yml
> +      - name: Publish Test Report
please replace `Publish Test Report` by

```
      - name: Check Surefire Report
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1.0.10
        with:
          fail_on_test_failures: true
          fail_if_no_tests: false
          skip_publishing: true.
          report_paths: '**/*-reports/TEST-*.xml'
```

2021-06-04 09:24 UTC, radtriste commented on .github/workflows/os_java_ci.yml
> +        uses: ginxo/action-surefire-report@BXMSPROD-1311
updated

2021-06-04 09:24 UTC, radtriste commented on .github/workflows/os_java_ci.yml
> +      - name: Publish Test Report
updated

2021-06-04 11:27 UTC, radtriste commented
@Ginxo Can you check it again ? :)

2021-06-04 12:04 UTC, rsynek commented
@radtriste there are growing concerns about the limits we are hitting with GHA. As @Ginxo kindly offered to organize a session about our long-term plans with GHA and Jenkins, could we please wait with merging this PR for the outcomes of the discussion? I assume you will be among the invitees.

2021-06-04 12:21 UTC, radtriste commented
@rsynek Sure. I was just harmonizing the build on GHAction as there was no "installation" of upstream repos (like kogito-runtimes) and so the PR check needed to wait for the upload of artifacts by the nightly else it was failing...

2021-06-04 12:45 UTC, triceo commented
I do not have an issue with this. The number of jobs stays the same. The runtime will grow slightly, but the benefit of no longer having to wait for nightly SNAPSHOTs outweighs that I think.

2021-06-04 14:40 UTC, radtriste commented
Indeed dependency is only on kogito-runtimes: https://github.com/kiegroup/kogito-pipelines/blob/master/.ci/project-dependencies.yaml#L5
and the upstream command is https://github.com/kiegroup/kogito-pipelines/blob/master/.ci/pull-request-config.yaml#L11
which takes 1 to 2 minutes on kogito-runtimes

2021-06-04 15:04 UTC, rsynek approved these changes

2021-06-04 15:07 UTC, rsynek commented
@radtriste the build of `kogito-runtimes` without tests is truly quick; please disregard my previous comment.

2021-06-07 09:24 UTC, Ginxo approved these changes
LGTM, thanks

2021-06-07 09:28 UTC, danielezonca approved these changes

2021-06-07 09:29 UTC, merged