Optimize SolutionDescriptor.findEntityDescriptor()
kiegroup/optaplanner pull request #1699
Opened 2021-12-01 13:50 UTC by yurloc

This PR offers one approach to address a trivial performance issue brought up in https://github.com/kiegroup/optaplanner/pull/1698#discussion_r759236750.

Use Optional.empty() instead of null as a value in the memoization map
to designate that the search for a descriptor has been made and none has
been found. As opposed to null meaning the search hasn't been made yet.

This proposal doesn't include the controversial internal API change that exposes `Optional` as the `findEntityDescriptor()` return type. This is simply achieved by returning `null` if the `Optional` representing the result of the search is empty.

### Referenced pull requests
Split from #1698.

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

We do "simple" maven builds, they are just basically maven commands, but just because we have multiple repositories related between them and one change could affect several of those projects by multiple pull requests, we use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.

[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by executing it locally. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>
</details>

2021-12-01 13:53 UTC, yurloc commented on optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java
> +            return Optional.empty();
Insert a log statement before this line and try with the Nurse Rostering example to see the effect.

2021-12-01 14:35 UTC, triceo approved these changes
I like this. That said, I will leave the final approval to @ge0ffrey, as he has his own opinions on `Optional`.

2021-12-06 19:48 UTC, ge0ffrey commented
Yea... I don't like the use of Optional outside of streams, where it was created for. IIRC Brian Goetz had the same advise on that.

I don't want to see this merged... Proliferating Optional will not make the code easier to read.

2021-12-07 10:50 UTC, ge0ffrey requested changes
I'don't want to introduce Optional, except for code that uses it to deal with stream operations that return zero or one results.
It doesn't make our code, as a whole, easier to read or to maintenance if this is introduced in some places. It doesn't make it faster.
And AFAIK, it's not its intended use.

2021-12-07 14:29 UTC, triceo commented
I still think that this change has value. Can we create a dummy entity descriptor which we would use in the map? The method should always return `null` though.

2021-12-08 09:44 UTC, yurloc commented
There is one thing that makes me hesitant to take the `Optional` approach.

In "Item 55: Return optionals judiciously", Joshua Bloch says:
> It is almost never appropriate to use an optional as a key, value, or element in a collection or array.

But I still think that in this case it's a correct and elegant usage. Btw, the fact that `Optional` is often used in `Stream` operation doesn't mean that it's limited to streams. It represents a value that is either present or missing and forces the user to check that before using the value. It's a good compromise between returning `null` and throwing a checked exception (to force the user to handle the case when the value is not present).

Nevertheless, the performance impact of the inefficient computation of the memoization map is unknown and probably negligible. So I consider this a premature optimization.

2021-12-08 09:44 UTC, closed without merging