PLANNER-2596 CI jobs: consistent naming
kiegroup/optaplanner pull request #1746
Opened 2021-12-27 09:13 UTC by Ginxo

2021-12-27 11:41 UTC, triceo approved these changes

2022-01-03 08:06 UTC, rsynek requested changes
The workflow

2022-01-03 08:06 UTC, rsynek commented on .github/workflows/os_java_ci.yml
> +      maven-version: ['3.8.1']
The workflow run complains that the file is not valid.
```suggestion
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11]
        maven-version: ['3.8.1']
```

2022-01-03 08:06 UTC, rsynek commented on .github/workflows/pull_request.yml
> +    name: Maven - ${{ matrix.os }} - ${{ matrix.java-version }}
This job seems to have been already broken; see https://github.com/kiegroup/optaplanner/actions/runs/1626493390/workflow

2022-01-03 09:19 UTC, Ginxo commented
fixed by 
![Screenshot from 2022-01-03 10-18-46](https://user-images.githubusercontent.com/25130444/147915149-b82a197f-4115-4a1c-afc2-61d206d97565.png)

2022-01-03 09:28 UTC, rsynek approved these changes

2022-01-03 10:07 UTC, yurloc commented
A couple of comments:
- "Maven" seems redundant. It doesn't add any extra information. It's _the build tool_ for the project and so it's in each combination.
- It's not exactly clear what 8 and 11 refer to. To avoid ambiguity, I would prefer "Java 11".

2022-01-03 10:08 UTC, yurloc commented on .github/workflows/jpa_integration_ci.yml
> +    name: Maven - ${{ matrix.os }} - ${{ matrix.java-version }}
```suggestion
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }}
```

2022-01-03 10:09 UTC, yurloc commented on .github/workflows/os_java_ci.yml
> +    name: Maven - ${{ matrix.os }} - ${{ matrix.java-version }}
```suggestion
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }}
```

2022-01-03 10:09 UTC, yurloc commented on .github/workflows/pull_request.yml
> +    name: Maven - ${{ matrix.os }} - ${{ matrix.java-version }}
```suggestion
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }}
```

2022-01-04 06:14 UTC, Ginxo commented
> A couple of comments:
> 
>     * "Maven" seems redundant. It doesn't add any extra information. It's _the build tool_ for the project and so it's in each combination.
> 
>     * It's not exactly clear what 8 and 11 refer to. To avoid ambiguity, I would prefer "Java 11".

I guess we should all agree on this and spread it to the rest of projects. @ge0ffrey @rsynek @mareknovotny wdyt?

2022-01-04 06:20 UTC, triceo commented
Sure, why not.

2022-01-04 06:39 UTC, rsynek commented
@Ginxo `Maven` is mostly redundant in the name, but in optaplanner-quickstarts, there are also `Gradle` builds.

+1 to use "Java ${version}"

2022-01-04 11:04 UTC, Ginxo commented
@rsynek @triceo @yurloc what about these options, please choose one of them

1. `${{ matrix.os }} - Maven/Java ${{ matrix.java-version }}` or `${{ matrix.os }} - Gradle/Java ${{ matrix.java-version }}`
2. `${{ matrix.os }} - Java ${{ matrix.java-version }}`
3. `Maven/Java ${{ matrix.java-version }} - ${{ matrix.os }}`
4. `Java ${{ matrix.java-version }} - ${{ matrix.os }}`

it is important to reach a consensus before spread it out for dozens of PRs, so please vote, thanks!

2022-01-04 11:15 UTC, triceo commented
I am fine with either, as long as it is consistent. If I absolutely have to pick, I pick 3.

2022-01-04 12:30 UTC, rsynek commented
The most important question for me is whether we could and should omit the `Maven` in the name. If we do, `Gradle` becomes an exception to the rule, which I would rather avoid.
How about making the build tool the least significant part of the name by moving it to the end?
`${{ matrix.os }} - Java ${{ matrix.java-version }} / (Maven|Gradle)`

2022-01-04 12:35 UTC, yurloc commented
> The most important question for me is whether we could and should omit the `Maven` in the name. If we do, `Gradle` becomes an exception to the rule, which I would rather avoid. How about making the build tool the least significant part of the name by moving it to the end? `${{ matrix.os }} - Java ${{ matrix.java-version }} / (Maven|Gradle)`

OK, but let's **consistently only use `-` as a delimiter**. Perfect is the enemy of good -- we can change the order of components later. Other than that Radek's proposal LGTM.

The corrected version with `-` delimiter:
`${{ matrix.os }} - Java ${{ matrix.java-version }} - (Maven|Gradle)`

2022-01-04 13:23 UTC, triceo commented
We're bikeshedding. Pick any one and apply it consistently, I'll be happy.

2022-01-05 07:00 UTC, Ginxo commented
done for all. I've even created a new PR for optaplanner main branch https://github.com/kiegroup/optaplanner/pull/1759 (since it was already merged)

2022-01-05 07:21 UTC, triceo approved these changes

2022-01-05 10:58 UTC, yurloc approved these changes

2022-01-05 21:55 UTC, merged