[BXMSPROD-1881] dependabot for main, 7.67.x and blue branches
kiegroup/optaplanner pull request #2321
Opened 2022-11-23 08:32 UTC by Ginxo

2022-11-23 08:34 UTC, kie-ci3 commented
**(tests) - optaplanner job** `#577` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.optaplanner/577/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverFactory.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverFactory.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsWorkaroundClasspathHelper.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsWorkaroundClasspathHelper.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ScanAnnotatedClassesConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ScanAnnotatedClassesConfig.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java left in tree.<br/>[2022-11-23T08:34:34.261Z] Auto-merging optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/SourcedVariableListener.java<br/>[2022-11-23T08:34:34.261Z] CONFLICT (content): Merge conflict in optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/SourcedVariableListener.java<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/StatefulVariableListener.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/StatefulVariableListener.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListener.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListener.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListenerAdapter.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListenerAdapter.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/AbstractCustomPhaseCommand.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/AbstractCustomPhaseCommand.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java left in tree.<br/>[2022-11-23T08:34:34.261Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreCalculator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreCalculator.java left in tree.<br/>[2022-11-23T08:34:34.262Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/AbstractIncrementalScoreCalculator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/AbstractIncrementalScoreCalculator.java left in tree.<br/>[2022-11-23T08:34:34.262Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java left in tree.<br/>[2022-11-23T08:34:34.262Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java left in tree.<br/>[2022-11-23T08:34:34.262Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/ [...]

2022-11-23 08:34 UTC, kie-ci3 commented
**(tests) - optaweb-vehicle-routing job** `#572` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaweb-vehicle-routing/572/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverFactory.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverFactory.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsWorkaroundClasspathHelper.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsWorkaroundClasspathHelper.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ScanAnnotatedClassesConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ScanAnnotatedClassesConfig.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java left in tree.<br/>[2022-11-23T08:34:37.017Z] Auto-merging optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/SourcedVariableListener.java<br/>[2022-11-23T08:34:37.017Z] CONFLICT (content): Merge conflict in optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/SourcedVariableListener.java<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/StatefulVariableListener.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/StatefulVariableListener.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListener.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListener.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListenerAdapter.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListenerAdapter.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/AbstractCustomPhaseCommand.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/AbstractCustomPhaseCommand.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreCalculator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreCalculator.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/AbstractIncrementalScoreCalculator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/AbstractIncrementalScoreCalculator.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java left in tree.<br/>[2022-11-23T08:34:37.017Z] CONFLICT (modify/delete):  [...]

2022-11-23 08:34 UTC, kie-ci3 commented
**(tests) - optaplanner-quickstarts job** `#578` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/pullrequest/job/optaplanner.tests.downstream.optaplanner-quickstarts/578/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverFactory.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverFactory.java left in tree.<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsWorkaroundClasspathHelper.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsWorkaroundClasspathHelper.java left in tree.<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ScanAnnotatedClassesConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ScanAnnotatedClassesConfig.java left in tree.<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java left in tree.<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java left in tree.<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java left in tree.<br/>[2022-11-23T08:34:40.368Z] Auto-merging optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/SourcedVariableListener.java<br/>[2022-11-23T08:34:40.368Z] CONFLICT (content): Merge conflict in optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/SourcedVariableListener.java<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/StatefulVariableListener.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/StatefulVariableListener.java left in tree.<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListener.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListener.java left in tree.<br/>[2022-11-23T08:34:40.368Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListenerAdapter.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/VariableListenerAdapter.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/AbstractCustomPhaseCommand.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/AbstractCustomPhaseCommand.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreCalculator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreCalculator.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/AbstractIncrementalScoreCalculator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/AbstractIncrementalScoreCalculator.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete): optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java deleted in HEAD and modified in e312b0ce9ede06d1b2c5fecf9a575e384c03d143.  Version e312b0ce9ede06d1b2c5fecf9a575e384c03d143 of optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java left in tree.<br/>[2022-11-23T08:34:40.369Z] CONFLICT (modify/delete):  [...]

2022-11-24 14:40 UTC, mareknovotny requested changes
here we need only main, 7.x and 7.67.x and 8.13.x to be scanned

2022-11-25 08:46 UTC, mareknovotny approved these changes

2022-11-25 09:12 UTC, merged